/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.findmaximum;

import java.util.Scanner;

public class Executer {
	public static void main(String[] args) {
		String numberOne;
		String numberTwo;
		String numberThree;
		Scanner scan = new Scanner(System.in);
		System.out.println("Welcome to Maximum finder System");
		System.out.println("Enter the First Number: ");
		numberOne = scan.next();
		System.out.println("Enter the Second Number: ");
		numberTwo = scan.next();
		System.out.println("Enter the Third Number: ");
		numberThree = scan.next();
	}
}