/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.findmaximumtest;

import org.junit.Test;

import com.capgemini.findmaximum.Executer;
import com.capgemini.findmaximum.FindMax;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class Testcase {
	@Test
	public void testCaseOne() {
		FindMax findMax = new FindMax();
		Integer data = findMax.find(5, 4, 1);
		Assert.assertEquals((Integer) 5, data);
	}

	@Test
	public void testCaseTwo() {
		FindMax findMax = new FindMax();
		Integer data = findMax.find(3, 4, 1);
		Assert.assertEquals((Integer) 4, data);
	}

	@Test
	public void testCaseThree() {
		FindMax findMax = new FindMax();
		Integer data = findMax.find(5, 4, 9);
		Assert.assertEquals((Integer) 9, data);
	}
}
