/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.findmaximumtest;

import org.junit.Test;

import com.capgemini.findmaximum.Executer;
import com.capgemini.findmaximum.FindMax;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class Testcase {
	@Test
	public void testCaseOne() {
		FindMax findMax = new FindMax();
		Float data = findMax.find(5.6f, 4.9f, 1.0f);
		Assert.assertEquals((Float) 5.6f, data);
	}

	@Test
	public void testCaseTwo() {
		FindMax findMax = new FindMax();
		Float data = findMax.find(3.1f, 4.2f, 1.3f);
		Assert.assertEquals((Float) 4.2f, data);
	}

	@Test
	public void testCaseThree() {
		FindMax findMax = new FindMax();
		Float data = findMax.find(5.4f, 4.2f, 9.3f);
		Assert.assertEquals((Float) 9.3f, data);
	}
}
