/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.findmaximumtest;

import org.junit.Test;

import com.capgemini.findmaximum.Executer;
import com.capgemini.findmaximum.FindMax;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class Testcase {
	@Test
	public void testCaseOne() {
		FindMax findMax = new FindMax();
		String data = findMax.find("c", "b", "a");
		Assert.assertEquals("c", data);
	}

	@Test
	public void testCaseTwo() {
		FindMax findMax = new FindMax();
		String data = findMax.find("b", "c", "a");
		Assert.assertEquals("c", data);
	}

	@Test
	public void testCaseThree() {
		FindMax findMax = new FindMax();
		String data = findMax.find("b", "a", "c");
		Assert.assertEquals("c", data);
	}
}
